In [1]:
import numpy as np
import pandas as pd
Data={ 'Name':['Ramesg','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

Name   Age  City
0   Ramesg   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [2]:
import numpy as np
import pandas as pd
Data={ 'Name':['Ramesg','Suresh','Sathish',None],
      'Age':[None,22,25,27],
      'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data)
df1

Name   Age  City
0   Ramesg   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [3]:
import numpy as np
import pandas as pd
Data={ 'Name':['Ramesg','Suresh','Sathish',Null],
      'Age':[Null,22,25,27],
      'City':['Pune','Pune',Null,'Hyd']}
df2=pd.DataFrame(Data)
df2

NameError: name 'Null' is not defined

In [ ]:
import numpy as np
import pandas as pd
Data={ 'Name':['Ramesg','Suresh','Sathish',null],
      'Age':[null,22,25,27],
      'City':['Pune','Pune',null,'Hyd']}
df3=pd.DataFrame(Data)
df3

In [ ]:
df.to_csv('data_missing.csv',index=False)

In [4]:
df1.to_csv('data_missing1.csv',index=False)

In [5]:
df.dtypes

Name     object
Age     float64
City     object
dtype: object

In [6]:
df1.dtypes

Name     object
Age     float64
City     object
dtype: object

**isnull**

In [7]:
df.isnull()

Name    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [8]:
df1.isnull()

Name    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [9]:
df.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

In [10]:
df1.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

**fillna**

In [11]:
df.fillna(30)  # not recomended

Name   Age  City
0   Ramesg  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [12]:
df['Age'].fillna(30)

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

- the above one is we are filling randomly
- all the columns are filled with random number
- it is not a good approach because in  a data we have different data types

In [13]:
df['Age'].fillna(30,inplace=True)
df

C:\Users\subra\AppData\Local\Temp\ipykernel_13092\3801372385.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(30,inplace=True)


Name   Age  City
0   Ramesg  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

**What is the difference between np.nan and None**

In [14]:
np.nan+5

nan

In [15]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [16]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [17]:
arr1

array([ 1.,  2., nan,  3.])

In [18]:
arr2

array([1, 2, None, 3], dtype=object)

In [19]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [20]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represent **float type**
- None represents **Object type**
- If the data operations related to maths then nan format is better

**Fill the value based on a specific column**

In [21]:
df['Name'].fillna('Amit')

0     Ramesg
1     Suresh
2    Sathish
3       Amit
Name: Name, dtype: object

**Fill with methods**
- whenever we are using methods no need to provide values

In [22]:
import numpy as np
import pandas as pd
Data={ 'Name':['Ramesg','Suresh','Sathish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

Name   Age  City
0   Ramesg   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

- pad
- bfill
- ffill
- backfill

In [23]:
# import warnings
# warnings.filterwarnings('ignore')
df.fillna(method='pad')

C:\Users\subra\AppData\Local\Temp\ipykernel_13092\2558497203.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')


Name   Age  City
0   Ramesg   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

**Note**
- to avoid warning
- we  import warnings
- warnings.filterwarnings('ignore') 

In [24]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')  # column wise

Name   Age  City
0   Ramesg   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [25]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)      # row wise 

Name     Age  City
0   Ramesg  Ramesg  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [26]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

Name   Age  City
0   Ramesg  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [27]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

Name   Age  City
0   Ramesg   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [28]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

Name   Age  City
0   Ramesg  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

**Note**
- pad=ffill
- bfill=backfill

In [29]:
age_mean=df['Age'].mean()
df['Age'].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [30]:
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [31]:
city_mode=df['City'].mode()
df['City'].fillna(city_mode)

0    Pune
1    Pune
2     NaN
3     Hyd
Name: City, dtype: object

In [32]:
city_mode

0    Pune
Name: City, dtype: object

In [33]:
mode=df['City'].mode()
mode

0    Pune
Name: City, dtype: object

**KNN Immputer**
- K-Nearest Neighbours
- Where K = hyper parameter which means the user can change
- Idea: Instead of taking all the samples average
    - First fix the neighbours number i.e k
    - Then find the neighbours using distance matric
    - Then take the average of those samples to fill the missing value

In [ ]:
# import sklearn
# from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import LabelEncoder
# from sklearn.impute import KNNImputer

In [35]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [ ]:
# import method
# save method
# apply fit_transform

In [36]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,
                    weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [37]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,
                    weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

==================EDA steps ===================
- 1.Read the data
- 2.Separate categorical  column and Numerical column
- 3.Data quick check
    - Shape, column, dtypes
- 4.Null value Analysis
    - A) Check if any Null Values are present
    - B) Fill the null values with Median or
          KNNImputer for Numerical column
    - C) Fill the null values with Mode for categorical columns
- 5.Do some data  preprocess if any column is corrupted
    - ex1: Numerical values in categorical column
    - ex2: Categorical values in Numerical column
- 6.Drop the ID type columns
    - which means a data has more unique labels
    - Drop the single value column
- 7.Categorical column Analysis
    - Frequency table
    - Bar chart
    - pie chart
- 8.Numerical column Analysis
    - Histogram
    - Distribution
    - Box plot
- 9.Outlier Analysis
    - Impute the outlier with Median
- 10.Find the corelation between numerical columns
    - Heat map
- 11.Convert Categorical to Numerical
    - A) Label Encoder
    - B) one Hot Encoder
- 12.Scale the data
    - A) Z standardaization
    - B) Normalization

**Note**
- By performing 12 steps , We achive 3 things
    - i. Cleaned the data
    - ii. Data in the form of complete  numerical
    - iii. We have some outstanding data 

- 13.We will try to select the important feature For ML Model
    - A) PCA : Principal component analysis (Covered in ML)
- Finally we achive 3 data sets
    - 1. Till Step-11
         with out scale but data in Numerical format
    - 2. Till Step-12
         With scaling data in Numerical format
    - 3. Till Step-13
         PCA data